### ISSUE TITLE
Use kebab-case instead of CamelCase for path

### ISSUE THREAD

**Issue by luaneyed** [9oelM/youtube-lite#25]
kebab-case is more readable than CamelCase in most cases.

**Comment by 9oelM** [comment]
that's right.

**Comment by 9oelM** [comment]
by the way, do you mean local system path? i.e. `SearchResults` folder -> `search-results`

**Comment by luaneyed** [comment]
I meant URL path.

**Comment by 9oelM** [comment]
Got that bro
