### ISSUE TITLE
Provide link for specific video

### ISSUE THREAD

**Issue by luaneyed** [9oelM/youtube-lite#26]
ex)

https://youtu.be/f5ShDNOqq1E
->
https://youtube-lite.js.org/video/f5ShDNOqq1E

And I guess `custom 'copy link' button` would be needed.

This link also can be very powerful advertisement!

**Comment by 9oelM** [comment]
@luaneyed are you talking about something like 'share' function?

**Comment by 9oelM** [comment]
There can be a link for specific video. 
e.g. 
[https://youtube-lite.js.org/videoPlayerView/Default/f5ShDNOqq1E](https://youtube-lite.js.org/videoPlayerView/Default/f5ShDNOqq1E)

but I could also just make a simpler version of the link like the one you suggested. I think it's good to make that.

**Comment by 9oelM** [comment]
As of PR #36, You can now use:
https://youtube-lite.js.org/video/f5ShDNOqq1E

**Comment by 9oelM** [comment]
Now we have to add a 'share' button.

**Comment by luaneyed** [comment]
Nice work!
How about shorten paths so that your code become the next line?
`<Redirect from="/v/:id" to="/video/Default/:id" />`

**Comment by 9oelM** [comment]
yeah. we can have both `v` and `video` like you said.

**Comment by 9oelM** [comment]
closed as of #42. For 'copy link' or share button, refer to #41.
