### ISSUE TITLE
Get playlist from url query

### ISSUE THREAD

**Issue by luaneyed** [9oelM/youtube-lite#39]
Now,

video without playlist -> `/video-player/Default/f5ShDNOqq1E`
video with playlist -> `/video-player/{playlist_id}/f5ShDNOqq1E`

And I think it should be

video without playlist -> `/video-player/f5ShDNOqq1E`
video with playlist -> `/video-player/f5ShDNOqq1E?list={playlist_id}`

because it seems like there is 'default playlist' currently

**Comment by 9oelM** [comment]
you are right that I need to put the playlist name as a query string. 
but I'm not really sure about 'video without playlist' because I think every user should be given an opportunity to add to a playlist immediately if he/she likes a video.

**Comment by luaneyed** [comment]
`Playlist View` => the video is included in some playlists of the user
But the converse is not always true.

The video is included in no playlist of the user => `Non-Playlist View`
But the converse is not always true. 

Users should be able to watch video included in some playlists in non-playlist view.
Besides, YouTube also does not redirect after adding a video to a playlist.
